version: 2.1
jobs:
  build:
    machine: true
    steps:
      - run: docker-compose build
      - run: docker-compose run --rm tf /var/tmp/terraform fmt -recursive /tf
      - slack/status:
          webhook: webhook

workflows:
  test:
    jobs:
      - build
