version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    machine: true
    steps:
      - run: docker-compose build
      - run: docker-compose run --rm tf /var/tmp/terraform fmt -recursive /tf
      - slack/status:
          webhook: webhook

workflows:
  test:
    jobs:
      - build
